
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Mongodb
    command: mkdir -p /workspace/data && mongod --dbpath /workspace/data

  - name: Logto
    init: docker compose pull
    command: ENDPOINT=$(gp url 3001) docker compose -p logto up
    env:
      TAG: prerelease
    
  - name: App
    init: yarn install
    command: yarn dev

ports:
  - port: 3333 
    visibility: public
    onOpen: open-browser
    
  - name: Logto
    description: The Logto core service
    port: 3001
    visibility: public

