version: "3.9"
services:
  mongo:
    image: mongo:4.2
    restart: unless-stopped
    #volumes:
      #- mongo_data:/data/db

  app:
    restart: unless-stopped
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo