// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    '[id]': typeof import('./components/[id].vue')['default']
    AttendanceList: typeof import('./components/AttendanceList.vue')['default']
    BackgroundFrame: typeof import('./components/BackgroundFrame.vue')['default']
    BackgroundFrameCenter: typeof import('./components/BackgroundFrameCenter.vue')['default']
    BackgroundFrameGrid: typeof import('./components/BackgroundFrameGrid.vue')['default']
    ButtonsFrame: typeof import('./components/ButtonsFrame.vue')['default']
    copy: typeof import('./components/Forms/EditMatchForm copy.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    DeletingMesageDialog: typeof import('./components/DeletingMesageDialog.vue')['default']
    EditMatchForm: typeof import('./components/Forms/EditMatchForm.vue')['default']
    EditTournamentForm: typeof import('./components/Forms/EditTournamentForm.vue')['default']
    EditTrainingForm: typeof import('./components/Forms/EditTrainingForm.vue')['default']
    ErrorMessage: typeof import('./components/ErrorMessage.vue')['default']
    ErrorMessageInfo: typeof import('./components/ErrorMessageInfo.vue')['default']
    EventStatistic: typeof import('./components/EventStatistic.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    LoadingCircle: typeof import('./components/LoadingCircle.vue')['default']
    MatchAndTournamentStatistic: typeof import('./components/MatchAndTournamentStatistic.vue')['default']
    MatchStatistic: typeof import('./components/MatchStatistic.vue')['default']
    MiniWhiteFrame: typeof import('./components/MiniWhiteFrame.vue')['default']
    MyCenterElement: typeof import('./components/MyCenterElement.vue')['default']
    MyGrid: typeof import('./components/MyGrid.vue')['default']
    NavMenu: typeof import('./components/NavMenu.vue')['default']
    NewEventForm: typeof import('./components/Forms/NewEventForm.vue')['default']
    NewEventStatisticForm: typeof import('./components/Forms/NewEventStatisticForm.vue')['default']
    NewParentForm: typeof import('./components/Forms/NewParentForm.vue')['default']
    NewPlayerForm: typeof import('./components/Forms/NewPlayerForm.vue')['default']
    NewProfileForm: typeof import('./components/Forms/NewProfileForm.vue')['default']
    NewSportsFacilityForm: typeof import('./components/Forms/NewSportsFacilityForm.vue')['default']
    NewTeamForm: typeof import('./components/Forms/NewTeamForm.vue')['default']
    NewTrainerForm: typeof import('./components/Forms/NewTrainerForm.vue')['default']
    PlayersStatistic: typeof import('./components/PlayersStatistic.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleAttribute: typeof import('./components/SingleAttribute.vue')['default']
    SingleButton: typeof import('./components/SingleButton.vue')['default']
    SingleEvent: typeof import('./components/SingleEvent.vue')['default']
    SingleInput: typeof import('./components/SingleInput.vue')['default']
    SingleStatistic: typeof import('./components/Statistic/SingleStatistic.vue')['default']
    SingleSummaryStatistic: typeof import('./components/Statistic/SingleSummaryStatistic.vue')['default']
    StatisticHeader: typeof import('./components/Statistic/StatisticHeader.vue')['default']
    StatisticSortOptions: typeof import('./components/Statistic/StatisticSortOptions.vue')['default']
    StatisticTable: typeof import('./components/Statistic/StatisticTable.vue')['default']
    TraininingAttendanceList: typeof import('./components/TraininingAttendanceList.vue')['default']
    WelcomeMenu: typeof import('./components/WelcomeMenu.vue')['default']
    YourProfile: typeof import('./components/YourProfile.vue')['default']
  }
}
