// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AttendanceList: typeof import('./components/AttendanceList.vue')['default']
    BackgroundFrame: typeof import('./components/BackgroundFrame.vue')['default']
    BackgroundFrameCenter: typeof import('./components/BackgroundFrameCenter.vue')['default']
    BackgroundFrameGrid: typeof import('./components/BackgroundFrameGrid.vue')['default']
    ButtonsFrame: typeof import('./components/ButtonsFrame.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    MatchStatistic: typeof import('./components/MatchStatistic.vue')['default']
    MatchStatisticForm: typeof import('./components/Forms/MatchStatisticForm.vue')['default']
    MiniWhiteFrame: typeof import('./components/MiniWhiteFrame.vue')['default']
    MyCenterElement: typeof import('./components/MyCenterElement.vue')['default']
    MyGrid: typeof import('./components/MyGrid.vue')['default']
    NavMenu: typeof import('./components/NavMenu.vue')['default']
    NewEventForm: typeof import('./components/Forms/NewEventForm.vue')['default']
    NewParentForm: typeof import('./components/Forms/NewParentForm.vue')['default']
    NewPlayerForm: typeof import('./components/Forms/NewPlayerForm.vue')['default']
    NewSportsFacilityForm: typeof import('./components/Forms/NewSportsFacilityForm.vue')['default']
    NewTeamForm: typeof import('./components/Forms/NewTeamForm.vue')['default']
    NewTrainerForm: typeof import('./components/Forms/NewTrainerForm.vue')['default']
    README: typeof import('./components/README.md')['default']
    SingleAttribute: typeof import('./components/SingleAttribute.vue')['default']
    SingleButton: typeof import('./components/SingleButton.vue')['default']
    SingleInput: typeof import('./components/SingleInput.vue')['default']
    WelcomeMenu: typeof import('./components/WelcomeMenu.vue')['default']
    YourProfile: typeof import('./components/YourProfile.vue')['default']
  }
}

export { }
